##server:
##  port: 3000
#
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE
#
org:
  springframework:
    cloud:
      bindings:
        boot:
          oauth2:
            enable: true

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          auth0:
#            client-id: <redacted>
#            client-secret: <redacted>>
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          auth0:
#            issuer-uri: https://dev-<redacted>.us.auth0.com/